(function(){'use strict';var n,aa=typeof Object.create=="function"?Object.create:function(a){function b(){}b.prototype=a;return new b},ba=typeof Object.defineProperties=="function"?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a};
function ca(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var p=ca(this);function r(a,b){if(b)a:{var c=p;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];if(!(e in c))break a;c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&b!=null&&ba(c,a,{configurable:!0,writable:!0,value:b})}}var da;
if(typeof Object.setPrototypeOf=="function")da=Object.setPrototypeOf;else{var ea;a:{var fa={a:!0},ja={};try{ja.__proto__=fa;ea=ja.a;break a}catch(a){}ea=!1}da=ea?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ka=da;
function v(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(ka)ka(a,b);else for(var c in b)if(c!="prototype")if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.K=b.prototype}function la(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}
function w(a){var b=typeof Symbol!="undefined"&&Symbol.iterator&&a[Symbol.iterator];if(b)return b.call(a);if(typeof a.length=="number")return{next:la(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function ma(a){return na(a,a)}function na(a,b){a.raw=b;Object.freeze&&(Object.freeze(a),Object.freeze(b));return a}function x(a,b){return Object.prototype.hasOwnProperty.call(a,b)}
var oa=typeof Object.assign=="function"?Object.assign:function(a,b){if(a==null)throw new TypeError("No nullish arg");a=Object(a);for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)x(d,e)&&(a[e]=d[e])}return a};r("Object.assign",function(a){return a||oa});function pa(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");}function y(){this.v=!1;this.j=null;this.o=void 0;this.h=1;this.l=this.u=0;this.B=this.i=null}
function qa(a){if(a.v)throw new TypeError("Generator is already running");a.v=!0}y.prototype.A=function(a){this.o=a};function ra(a,b){a.i={X:b,Y:!0};a.h=a.u||a.l}y.prototype.getNextAddressJsc=function(){return this.h};y.prototype.getYieldResultJsc=function(){return this.o};y.prototype.return=function(a){this.i={return:a};this.h=this.l};y.prototype["return"]=y.prototype.return;y.prototype.L=function(a){this.i={J:a};this.l<a?(this.h=a,this.i=null):this.h=this.l};
y.prototype.jumpThroughFinallyBlocks=y.prototype.L;y.prototype.m=function(a,b){this.h=b;return{value:a}};y.prototype.yield=y.prototype.m;y.prototype.fa=function(a,b){a=w(a);var c=a.next();pa(c);if(c.done)this.o=c.value,this.h=b;else return this.j=a,this.m(c.value,b)};y.prototype.yieldAll=y.prototype.fa;y.prototype.J=function(a){this.h=a};y.prototype.jumpTo=y.prototype.J;y.prototype.C=function(){this.h=0};y.prototype.jumpToEnd=y.prototype.C;
y.prototype.da=function(a,b){this.u=a;b!=void 0&&(this.l=b)};y.prototype.setCatchFinallyBlocks=y.prototype.da;y.prototype.ea=function(a){this.u=0;this.l=a||0};y.prototype.setFinallyBlock=y.prototype.ea;y.prototype.U=function(a,b){this.h=a;this.u=b||0};y.prototype.leaveTryBlock=y.prototype.U;y.prototype.D=function(a){this.u=a||0;a=this.i.X;this.i=null;return a};y.prototype.enterCatchBlock=y.prototype.D;
y.prototype.F=function(a,b,c){c?this.B[c]=this.i:this.B=[this.i];this.u=a||0;this.l=b||0;this.i=null};y.prototype.enterFinallyBlock=y.prototype.F;y.prototype.P=function(a,b){b=this.B.splice(b||0)[0];(b=this.i=this.i||b)?b.Y?this.h=this.u||this.l:b.J!=void 0&&this.l<b.J?(this.h=b.J,this.i=null):this.h=this.l:this.h=a};y.prototype.leaveFinallyBlock=y.prototype.P;y.prototype.I=function(a){return new sa(a)};y.prototype.forIn=y.prototype.I;
function sa(a){this.j=a;this.h=[];for(var b in a)this.h.push(b);this.h.reverse()}sa.prototype.i=function(){for(;this.h.length>0;){var a=this.h.pop();if(a in this.j)return a}return null};sa.prototype.getNext=sa.prototype.i;function ta(a){this.h=new y;this.i=a}function ua(a,b){qa(a.h);var c=a.h.j;if(c)return va(a,"return"in c?c["return"]:function(d){return{value:d,done:!0}},b,a.h.return);a.h.return(b);return z(a)}
function va(a,b,c,d){try{var e=b.call(a.h.j,c);pa(e);if(!e.done)return a.h.v=!1,e;var h=e.value}catch(f){return a.h.j=null,ra(a.h,f),z(a)}a.h.j=null;d.call(a.h,h);return z(a)}function z(a){for(;a.h.h;)try{var b=a.i(a.h);if(b)return a.h.v=!1,{value:b.value,done:!1}}catch(c){a.h.o=void 0,ra(a.h,c)}a.h.v=!1;if(a.h.i){b=a.h.i;a.h.i=null;if(b.Y)throw b.X;return{value:b.return,done:!0}}return{value:void 0,done:!0}}
function wa(a){this.next=function(b){qa(a.h);a.h.j?b=va(a,a.h.j.next,b,a.h.A):(a.h.A(b),b=z(a));return b};this.throw=function(b){qa(a.h);if(a.h.j){var c=a.h.j["throw"];if(c)var d=va(a,c,b,a.h.A);else{b=a.h.j;a.h.j=null;try{b["return"]&&(d=b["return"](),pa(d)),ra(a.h,new TypeError("The iterator does not provide a 'throw' method."))}catch(e){ra(a.h,e)}d=z(a)}}else ra(a.h,b),d=z(a);return d};this.return=function(b){return ua(a,b)};this[Symbol.iterator]=function(){return this}}
function xa(a){function b(d){return a.next(d)}function c(d){return a.throw(d)}return new Promise(function(d,e){function h(f){f.done?d(f.value):Promise.resolve(f.value).then(b,c).then(h,e)}h(a.next())})}function A(a){return xa(new wa(new ta(a)))}function ya(){for(var a=Number(this),b=[],c=a;c<arguments.length;c++)b[c-a]=arguments[c];return b}r("globalThis",function(a){return a||p});
r("Symbol",function(a){function b(h){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(h||"")+"_"+e++,h)}function c(h,f){this.h=h;ba(this,"description",{configurable:!0,writable:!0,value:f})}if(a)return a;c.prototype.toString=function(){return this.h};var d="jscomp_symbol_"+(Math.random()*1E9>>>0)+"_",e=0;return b});
r("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");ba(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return za(la(this))}});return a});function za(a){a={next:a};a[Symbol.iterator]=function(){return this};return a}
r("Promise",function(a){function b(f){this.h=0;this.j=void 0;this.i=[];this.u=!1;var g=this.l();try{f(g.resolve,g.reject)}catch(k){g.reject(k)}}function c(){this.h=null}function d(f){return f instanceof b?f:new b(function(g){g(f)})}if(a)return a;c.prototype.i=function(f){if(this.h==null){this.h=[];var g=this;this.j(function(){g.m()})}this.h.push(f)};var e=p.setTimeout;c.prototype.j=function(f){e(f,0)};c.prototype.m=function(){for(;this.h&&this.h.length;){var f=this.h;this.h=[];for(var g=0;g<f.length;++g){var k=
f[g];f[g]=null;try{k()}catch(l){this.l(l)}}}this.h=null};c.prototype.l=function(f){this.j(function(){throw f;})};b.prototype.l=function(){function f(l){return function(m){k||(k=!0,l.call(g,m))}}var g=this,k=!1;return{resolve:f(this.D),reject:f(this.m)}};b.prototype.D=function(f){if(f===this)this.m(new TypeError("A Promise cannot resolve to itself"));else if(f instanceof b)this.I(f);else{a:switch(typeof f){case "object":var g=f!=null;break a;case "function":g=!0;break a;default:g=!1}g?this.C(f):this.o(f)}};
b.prototype.C=function(f){var g=void 0;try{g=f.then}catch(k){this.m(k);return}typeof g=="function"?this.L(g,f):this.o(f)};b.prototype.m=function(f){this.v(2,f)};b.prototype.o=function(f){this.v(1,f)};b.prototype.v=function(f,g){if(this.h!=0)throw Error("Cannot settle("+f+", "+g+"): Promise already settled in state"+this.h);this.h=f;this.j=g;this.h===2&&this.F();this.A()};b.prototype.F=function(){var f=this;e(function(){if(f.B()){var g=p.console;typeof g!=="undefined"&&g.error(f.j)}},1)};b.prototype.B=
function(){if(this.u)return!1;var f=p.CustomEvent,g=p.Event,k=p.dispatchEvent;if(typeof k==="undefined")return!0;typeof f==="function"?f=new f("unhandledrejection",{cancelable:!0}):typeof g==="function"?f=new g("unhandledrejection",{cancelable:!0}):(f=p.document.createEvent("CustomEvent"),f.initCustomEvent("unhandledrejection",!1,!0,f));f.promise=this;f.reason=this.j;return k(f)};b.prototype.A=function(){if(this.i!=null){for(var f=0;f<this.i.length;++f)h.i(this.i[f]);this.i=null}};var h=new c;b.prototype.I=
function(f){var g=this.l();f.S(g.resolve,g.reject)};b.prototype.L=function(f,g){var k=this.l();try{f.call(g,k.resolve,k.reject)}catch(l){k.reject(l)}};b.prototype.then=function(f,g){function k(t,u){return typeof t=="function"?function(K){try{l(t(K))}catch(G){m(G)}}:u}var l,m,q=new b(function(t,u){l=t;m=u});this.S(k(f,l),k(g,m));return q};b.prototype.catch=function(f){return this.then(void 0,f)};b.prototype.S=function(f,g){function k(){switch(l.h){case 1:f(l.j);break;case 2:g(l.j);break;default:throw Error("Unexpected state: "+
l.h);}}var l=this;this.i==null?h.i(k):this.i.push(k);this.u=!0};b.resolve=d;b.reject=function(f){return new b(function(g,k){k(f)})};b.race=function(f){return new b(function(g,k){for(var l=w(f),m=l.next();!m.done;m=l.next())d(m.value).S(g,k)})};b.all=function(f){var g=w(f),k=g.next();return k.done?d([]):new b(function(l,m){function q(K){return function(G){t[K]=G;u--;u==0&&l(t)}}var t=[],u=0;do t.push(void 0),u++,d(k.value).S(q(t.length-1),m),k=g.next();while(!k.done)})};return b});
r("Symbol.dispose",function(a){return a?a:Symbol("Symbol.dispose")});
r("WeakMap",function(a){function b(k){this.h=(g+=Math.random()+1).toString();if(k){k=w(k);for(var l;!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}}function c(){}function d(k){var l=typeof k;return l==="object"&&k!==null||l==="function"}function e(k){if(!x(k,f)){var l=new c;ba(k,f,{value:l})}}function h(k){var l=Object[k];l&&(Object[k]=function(m){if(m instanceof c)return m;Object.isExtensible(m)&&e(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),
m=new a([[k,2],[l,3]]);if(m.get(k)!=2||m.get(l)!=3)return!1;m.delete(k);m.set(l,4);return!m.has(k)&&m.get(l)==4}catch(q){return!1}}())return a;var f="$jscomp_hidden_"+Math.random();h("freeze");h("preventExtensions");h("seal");var g=0;b.prototype.set=function(k,l){if(!d(k))throw Error("Invalid WeakMap key");e(k);if(!x(k,f))throw Error("WeakMap key fail: "+k);k[f][this.h]=l;return this};b.prototype.get=function(k){return d(k)&&x(k,f)?k[f][this.h]:void 0};b.prototype.has=function(k){return d(k)&&x(k,
f)&&x(k[f],this.h)};b.prototype.delete=function(k){return d(k)&&x(k,f)&&x(k[f],this.h)?delete k[f][this.h]:!1};return b});
r("Map",function(a){function b(){var g={};return g.H=g.next=g.head=g}function c(g,k){var l=g[1];return za(function(){if(l){for(;l.head!=g[1];)l=l.H;for(;l.next!=l.head;)return l=l.next,{done:!1,value:k(l)};l=null}return{done:!0,value:void 0}})}function d(g,k){var l=k&&typeof k;l=="object"||l=="function"?h.has(k)?l=h.get(k):(l=""+ ++f,h.set(k,l)):l="p_"+k;var m=g[0][l];if(m&&x(g[0],l))for(g=0;g<m.length;g++){var q=m[g];if(k!==k&&q.key!==q.key||k===q.key)return{id:l,list:m,index:g,entry:q}}return{id:l,
list:m,index:-1,entry:void 0}}function e(g){this[0]={};this[1]=b();this.size=0;if(g){g=w(g);for(var k;!(k=g.next()).done;)k=k.value,this.set(k[0],k[1])}}if(function(){if(!a||typeof a!="function"||!a.prototype.entries||typeof Object.seal!="function")return!1;try{var g=Object.seal({x:4}),k=new a(w([[g,"s"]]));if(k.get(g)!="s"||k.size!=1||k.get({x:4})||k.set({x:4},"t")!=k||k.size!=2)return!1;var l=k.entries(),m=l.next();if(m.done||m.value[0]!=g||m.value[1]!="s")return!1;m=l.next();return m.done||m.value[0].x!=
4||m.value[1]!="t"||!l.next().done?!1:!0}catch(q){return!1}}())return a;var h=new WeakMap;e.prototype.set=function(g,k){g=g===0?0:g;var l=d(this,g);l.list||(l.list=this[0][l.id]=[]);l.entry?l.entry.value=k:(l.entry={next:this[1],H:this[1].H,head:this[1],key:g,value:k},l.list.push(l.entry),this[1].H.next=l.entry,this[1].H=l.entry,this.size++);return this};e.prototype.delete=function(g){g=d(this,g);return g.entry&&g.list?(g.list.splice(g.index,1),g.list.length||delete this[0][g.id],g.entry.H.next=g.entry.next,
g.entry.next.H=g.entry.H,g.entry.head=null,this.size--,!0):!1};e.prototype.clear=function(){this[0]={};this[1]=this[1].H=b();this.size=0};e.prototype.has=function(g){return!!d(this,g).entry};e.prototype.get=function(g){return(g=d(this,g).entry)&&g.value};e.prototype.entries=function(){return c(this,function(g){return[g.key,g.value]})};e.prototype.keys=function(){return c(this,function(g){return g.key})};e.prototype.values=function(){return c(this,function(g){return g.value})};e.prototype.forEach=
function(g,k){for(var l=this.entries(),m;!(m=l.next()).done;)m=m.value,g.call(k,m[1],m[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var f=0;return e});function Aa(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var h=c++;return{value:b(h,a[h]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[Symbol.iterator]=function(){return e};return e}r("Array.prototype.entries",function(a){return a?a:function(){return Aa(this,function(b,c){return[b,c]})}});
r("Array.prototype.keys",function(a){return a?a:function(){return Aa(this,function(b){return b})}});r("Number.isFinite",function(a){return a?a:function(b){return typeof b!=="number"?!1:!isNaN(b)&&b!==Infinity&&b!==-Infinity}});r("Array.prototype.find",function(a){return a?a:function(b,c){a:{var d=this;d instanceof String&&(d=String(d));for(var e=d.length,h=0;h<e;h++){var f=d[h];if(b.call(c,f,h,d)){b=f;break a}}b=void 0}return b}});
r("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)x(b,d)&&c.push([d,b[d]]);return c}});r("Array.from",function(a){return a?a:function(b,c,d){c=c!=null?c:function(g){return g};var e=[],h=typeof Symbol!="undefined"&&Symbol.iterator&&b[Symbol.iterator];if(typeof h=="function"){b=h.call(b);for(var f=0;!(h=b.next()).done;)e.push(c.call(d,h.value,f++))}else for(h=b.length,f=0;f<h;f++)e.push(c.call(d,b[f],f));return e}});r("Number.MAX_SAFE_INTEGER",function(){return 9007199254740991});
r("Number.MIN_SAFE_INTEGER",function(){return-9007199254740991});r("Number.isInteger",function(a){return a?a:function(b){return Number.isFinite(b)?b===Math.floor(b):!1}});r("Object.is",function(a){return a?a:function(b,c){return b===c?b!==0||1/b===1/c:b!==b&&c!==c}});r("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(c<0&&(c=Math.max(c+e,0));c<e;c++){var h=d[c];if(h===b||Object.is(h,b))return!0}return!1}});
r("String.prototype.includes",function(a){return a?a:function(b,c){if(this==null)throw new TypeError("The 'this' value for String.prototype.includes must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype.includes must not be a regular expression");return(this+"").indexOf(b,c||0)!==-1}});r("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)x(b,d)&&c.push(b[d]);return c}});
r("Number.isNaN",function(a){return a?a:function(b){return typeof b==="number"&&isNaN(b)}});r("Array.prototype.values",function(a){return a?a:function(){return Aa(this,function(b,c){return c})}});
r("String.prototype.replaceAll",function(a){return a?a:function(b,c){if(b instanceof RegExp&&!b.global)throw new TypeError("String.prototype.replaceAll called with a non-global RegExp argument.");return b instanceof RegExp?this.replace(b,c):this.replace(new RegExp(String(b).replace(/([-()\[\]{}+?*.$\^|,:#<!\\])/g,"\\$1").replace(/\x08/g,"\\x08"),"g"),c)}});/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var Ba=Ba||{},B=this||self;function Ca(a,b){a=a.split(".");for(var c=B,d;a.length&&(d=a.shift());)a.length||b===void 0?c[d]&&c[d]!==Object.prototype[d]?c=c[d]:c=c[d]={}:c[d]=b}function Da(a,b){a=a.split(".");b=b||B;for(var c=0;c<a.length;c++)if(b=b[a[c]],b==null)return null;return b}function Ea(a){var b=typeof a;return b!="object"?b:a?Array.isArray(a)?"array":b:"null"}function Fa(a){var b=Ea(a);return b=="array"||b=="object"&&typeof a.length=="number"}
function Ga(a){var b=typeof a;return b=="object"&&a!=null||b=="function"}var Ha="closure_uid_"+(Math.random()*1E9>>>0),Ia=0;function Ja(a,b,c){return a.call.apply(a.bind,arguments)}function Ka(a,b,c){if(!a)throw Error();if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}
function C(a,b,c){C=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?Ja:Ka;return C.apply(null,arguments)}function La(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}function Ma(a){(0,eval)(a)}
function D(a,b){function c(){}c.prototype=b.prototype;a.K=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Ea=function(d,e,h){for(var f=Array(arguments.length-2),g=2;g<arguments.length;g++)f[g-2]=arguments[g];return b.prototype[e].apply(d,f)}};function E(a,b){if(Error.captureStackTrace)Error.captureStackTrace(this,E);else{var c=Error().stack;c&&(this.stack=c)}a&&(this.message=String(a));b!==void 0&&(this.cause=b);this.h=!0}D(E,Error);E.prototype.name="CustomError";var Na;var Oa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(typeof a==="string")return typeof b!=="string"||b.length!=1?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Qa=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=typeof a==="string"?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)},Ra=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=typeof a==="string"?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1};function Sa(a,b){b=Oa(a,b);var c;(c=b>=0)&&Array.prototype.splice.call(a,b,1);return c}function Ta(a){var b=a.length;if(b>0){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function Ua(a){var b=Da("window.location.href");a==null&&(a='Unknown Error of type "null/undefined"');if(typeof a==="string")return{message:a,name:"Unknown error",lineNumber:"Not available",fileName:b,stack:"Not available"};var c=!1;try{var d=a.lineNumber||a.line||"Not available"}catch(f){d="Not available",c=!0}try{var e=a.fileName||a.filename||a.sourceURL||B.$googDebugFname||b}catch(f){e="Not available",c=!0}b=Va(a);if(!(!c&&a.lineNumber&&a.fileName&&a.stack&&a.message&&a.name)){c=a.message;if(c==
null){if(a.constructor&&a.constructor instanceof Function){if(a.constructor.name)c=a.constructor.name;else if(c=a.constructor,Wa[c])c=Wa[c];else{c=String(c);if(!Wa[c]){var h=/function\s+([^\(]+)/m.exec(c);Wa[c]=h?h[1]:"[Anonymous]"}c=Wa[c]}c='Unknown Error of type "'+c+'"'}else c="Unknown Error of unknown type";typeof a.toString==="function"&&Object.prototype.toString!==a.toString&&(c+=": "+a.toString())}return{message:c,name:a.name||"UnknownError",lineNumber:d,fileName:e,stack:b||"Not available"}}return{message:a.message,
name:a.name,lineNumber:a.lineNumber,fileName:a.fileName,stack:b}}
function Va(a,b){b||(b={});b[Xa(a)]=!0;var c=a.stack||"",d=a.cause;d&&!b[Xa(d)]&&(c+="\nCaused by: ",d.stack&&d.stack.indexOf(d.toString())==0||(c+=typeof d==="string"?d:d.message+"\n"),c+=Va(d,b));a=a.errors;if(Array.isArray(a)){d=1;var e;for(e=0;e<a.length&&!(d>4);e++)b[Xa(a[e])]||(c+="\nInner error "+d++ +": ",a[e].stack&&a[e].stack.indexOf(a[e].toString())==0||(c+=typeof a[e]==="string"?a[e]:a[e].message+"\n"),c+=Va(a[e],b));e<a.length&&(c+="\n... "+(a.length-e)+" more inner errors")}return c}
function Xa(a){var b="";typeof a.toString==="function"&&(b=""+a);return b+a.stack}var Wa={};function Ya(a,b){for(var c in a)b.call(void 0,a[c],c,a)}function Za(a){var b={},c;for(c in a)b[c]=a[c];return b}var $a="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function ab(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var h=0;h<$a.length;h++)c=$a[h],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};/*

 Copyright Google LLC
 SPDX-License-Identifier: Apache-2.0
*/
var bb=globalThis.trustedTypes,cb;function db(){var a=null;if(!bb)return a;try{var b=function(c){return c};a=bb.createPolicy("asx-frontend#html",{createHTML:b,createScript:b,createScriptURL:b})}catch(c){}return a};function eb(a){this.h=a}eb.prototype.toString=function(){return this.h+""};function fb(a){var b;cb===void 0&&(cb=db());a=(b=cb)?b.createScriptURL(a):a;return new eb(a)}function gb(a){if(a instanceof eb)return a.h;throw Error("");};var hb=/^\s*(?!javascript:)(?:[\w+.-]+:|[^:/?#]*(?:[/?#]|$))/i;function ib(a,b){b=hb.test(b)?b:void 0;b!==void 0&&a.open(b,void 0,void 0)}function jb(a){a=a===void 0?document:a;var b,c;a=(c=(b=a).querySelector)==null?void 0:c.call(b,"script[nonce]");return a==null?"":a.nonce||a.getAttribute("nonce")||""};function kb(a,b){a.src=gb(b);(b=jb(a.ownerDocument))&&a.setAttribute("nonce",b)};var lb,mb=Da("CLOSURE_FLAGS"),nb=mb&&mb[748402147];lb=nb!=null?nb:!0;function ob(){var a=B.navigator;return a&&(a=a.userAgent)?a:""};var pb=ob().toLowerCase().indexOf("webkit")!=-1&&ob().indexOf("Edge")==-1&&ob().indexOf("Mobile")!=-1;function qb(a){var b=ya.apply(1,arguments);if(b.length===0)return fb(a[0]);for(var c=a[0],d=0;d<b.length;d++)c+=encodeURIComponent(b[d])+a[d+1];return fb(c)};function rb(a,b){Ya(b,function(c,d){d=="style"?a.style.cssText=c:d=="class"?a.className=c:d=="for"?a.htmlFor=c:sb.hasOwnProperty(d)?a.setAttribute(sb[d],c):d.lastIndexOf("aria-",0)==0||d.lastIndexOf("data-",0)==0?a.setAttribute(d,c):a[d]=c})}var sb={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
function tb(a,b,c){var d=arguments,e=document,h=d[1],f=ub(e,String(d[0]));h&&(typeof h==="string"?f.className=h:Array.isArray(h)?f.className=h.join(" "):rb(f,h));d.length>2&&vb(e,f,d,2);return f}
function vb(a,b,c,d){function e(g){g&&b.appendChild(typeof g==="string"?a.createTextNode(g):g)}for(;d<c.length;d++){var h=c[d];if(!Fa(h)||Ga(h)&&h.nodeType>0)e(h);else{a:{if(h&&typeof h.length=="number"){if(Ga(h)){var f=typeof h.item=="function"||typeof h.item=="string";break a}if(typeof h==="function"){f=typeof h.item=="function";break a}}f=!1}Qa(f?Ta(h):h,e)}}}function ub(a,b){b=String(b);a.contentType==="application/xhtml+xml"&&(b=b.toLowerCase());return a.createElement(b)}
function wb(a){return a.nodeType==9?a:a.ownerDocument||a.document}function xb(a){this.h=a||B.document||document}xb.prototype.append=function(a,b){vb(wb(a),a,arguments,1)};function yb(a){B.setTimeout(function(){throw a;},0)};var zb=typeof B.BigInt==="function"&&typeof B.BigInt(0)==="bigint";var Ab=Number.MIN_SAFE_INTEGER.toString(),Bb=zb?BigInt(Number.MIN_SAFE_INTEGER):void 0,Cb=Number.MAX_SAFE_INTEGER.toString(),Db=zb?BigInt(Number.MAX_SAFE_INTEGER):void 0;function Eb(a,b){if(a.length>b.length)return!1;if(a.length<b.length||a===b)return!0;for(var c=0;c<a.length;c++){var d=a[c],e=b[c];if(d>e)return!1;if(d<e)return!0}};var Fb=typeof Symbol==="function"&&typeof Symbol()==="symbol";function Gb(a,b,c){return typeof Symbol==="function"&&typeof Symbol()==="symbol"?(c===void 0?0:c)&&Symbol.for&&a?Symbol.for(a):a!=null?Symbol(a):Symbol():b}var Hb=Gb("jas",void 0,!0),Ib=Gb(void 0,"0actk"),Jb=Gb("m_m","Ga",!0);var Kb=Math.max,Lb=Kb.apply,Mb=Object.values({wa:1,va:2,ua:4,Ba:8,Da:16,za:32,oa:64,sa:128,qa:256,Ca:512,ra:1024,ta:2048,Aa:4096,xa:8192}),Nb;if(Mb instanceof Array)Nb=Mb;else{for(var Pb=w(Mb),Qb,Rb=[];!(Qb=Pb.next()).done;)Rb.push(Qb.value);Nb=Rb}Lb.call(Kb,Math,Nb);var Sb={ma:{value:0,configurable:!0,writable:!0,enumerable:!1}},Tb=Object.defineProperties,F=Fb?Hb:"ma";function Ub(a,b){Fb||F in a||Tb(a,Sb);a[F]|=b}function Vb(a,b){Fb||F in a||Tb(a,Sb);a[F]=b};var Wb={};function Xb(a,b){return b===void 0?a.i!==Yb&&!!(2&(a.h[F]|0)):!!(2&b)&&a.i!==Yb}var Yb={};var Zb=void 0;function $b(a){return a.displayName||a.name||"unknown type name"};function ac(a){return a};function bc(a,b,c,d){var e=d!==void 0;d=!!d;var h=[],f=a.length,g=4294967295,k=!1,l=!!(b&64),m=l?b&128?0:-1:void 0;if(!(b&1)){var q=f&&a[f-1];q!=null&&typeof q==="object"&&q.constructor===Object?(f--,g=f):q=void 0;if(l&&!(b&128)&&!e){k=!0;var t;g=((t=cc)!=null?t:ac)(g-m,m,a,q,void 0)+m}}b=void 0;for(e=0;e<f;e++)if(t=a[e],t!=null&&(t=c(t,d))!=null)if(l&&e>=g){var u=e-m,K=void 0;((K=b)!=null?K:b={})[u]=t}else h[e]=t;if(q)for(var G in q)a=q[G],a!=null&&(a=c(a,d))!=null&&(f=+G,e=void 0,l&&!Number.isNaN(f)&&
(e=f+m)<g?h[e]=a:(f=void 0,((f=b)!=null?f:b={})[G]=a));b&&(k?h.push(b):h[g]=b);return h}function dc(a){switch(typeof a){case "number":return Number.isFinite(a)?a:""+a;case "bigint":return(zb?a>=Bb&&a<=Db:a[0]==="-"?Eb(a,Ab):Eb(a,Cb))?Number(a):""+a;case "boolean":return a?1:0;case "object":if(Array.isArray(a)){var b=a[F]|0;return a.length===0&&b&1?void 0:bc(a,b,dc)}if(a!=null&&a[Jb]===Wb)return ec(a);return}return a}var cc;function ec(a){a=a.h;return bc(a,a[F]|0,dc)};function fc(a,b,c,d){d=d===void 0?0:d;if(a==null){var e=32;c?(a=[c],e|=128):a=[];b&&(e=e&-16760833|(b&1023)<<14)}else{if(!Array.isArray(a))throw Error("narr");e=a[F]|0;if(lb&&1&e)throw Error("rfarr");2048&e&&!(2&e)&&hc();if(e&256)throw Error("farr");if(e&64)return(e|d)!==e&&Vb(a,e|d),a;if(c&&(e|=128,c!==a[0]))throw Error("mid");a:{c=a;e|=64;var h=c.length;if(h){var f=h-1,g=c[f];if(g!=null&&typeof g==="object"&&g.constructor===Object){b=e&128?0:-1;f-=b;if(f>=1024)throw Error("pvtlmt");for(var k in g)h=
+k,h<f&&(c[h+b]=g[k],delete g[k]);e=e&-16760833|(f&1023)<<14;break a}}if(b){k=Math.max(b,h-(e&128?0:-1));if(k>1024)throw Error("spvt");e=e&-16760833|(k&1023)<<14}}}Vb(a,e|64|d);return a}function hc(){if(lb)throw Error("carr");if(Ib!=null){var a;var b=(a=Zb)!=null?a:Zb={};a=b[Ib]||0;a>=5||(b[Ib]=a+1,b=Error(),b.__closure__error__context__984382||(b.__closure__error__context__984382={}),b.__closure__error__context__984382.severity="incident",yb(b))}};function ic(a,b){if(typeof a!=="object")return a;if(Array.isArray(a)){var c=a[F]|0;a.length===0&&c&1?a=void 0:c&2||(!b||4096&c||16&c?a=jc(a,c,!1,b&&!(c&16)):(Ub(a,34),c&4&&Object.freeze(a)));return a}if(a!=null&&a[Jb]===Wb)return b=a.h,c=b[F]|0,Xb(a,c)?a:kc(a,b,c)?lc(a,b):jc(b,c)}function lc(a,b,c){a=new a.constructor(b);c&&(a.i=Yb);a.j=Yb;return a}function jc(a,b,c,d){d!=null||(d=!!(34&b));a=bc(a,b,ic,d);d=32;c&&(d|=2);b=b&16769217|d;Vb(a,b);return a}
function mc(a){if(a.i!==Yb)return!1;var b=a.h;b=jc(b,b[F]|0);Ub(b,2048);a.h=b;a.i=void 0;a.j=void 0;return!0}function nc(a){if(!mc(a)&&Xb(a,a.h[F]|0))throw Error();}function oc(a,b){b===void 0&&(b=a[F]|0);b&32&&!(b&4096)&&Vb(a,b|4096)}function kc(a,b,c){return c&2?!0:c&32&&!(c&4096)?(Vb(b,c|2),a.i=Yb,!0):!1};function pc(a,b,c){if(b===-1)return null;var d=b+-1,e=a.length-1;if(!(e<0)){if(d>=e){var h=a[e];if(h!=null&&typeof h==="object"&&h.constructor===Object){e=h[b];var f=!0}else if(d===e)e=h;else return}else e=a[d];if(c&&e!=null){c=c(e);if(c==null)return c;if(!Object.is(c,e))return f?h[b]=c:a[d]=c,c}return e}}
function qc(a,b,c,d){var e=c+-1,h=a.length-1;if(h>=0&&e>=h){var f=a[h];if(f!=null&&typeof f==="object"&&f.constructor===Object)return f[c]=d,b}if(e<=h)return a[e]=d,b;if(d!==void 0){var g;h=((g=b)!=null?g:b=a[F]|0)>>14&1023||536870912;c>=h?d!=null&&(e={},a[h+-1]=(e[c]=d,e)):a[e]=d}return b}
function rc(a,b){var c=sc,d=!1,e=pc(a,1,function(h){if(h!=null&&h[Jb]===Wb)var f=h;else if(Array.isArray(h)){f=h[F]|0;var g=f|b&32;g|=b&2;g!==f&&Vb(h,g);f=new c(h)}else f=void 0;d=f!==h&&f!=null;return f});if(e!=null)return d&&!Xb(e)&&oc(a,b),e}function H(a,b){var c=c===void 0?!1:c;Object.isExtensible(a);a=pc(a.h,b);a=a!==null?a:void 0;a=a==null||typeof a==="boolean"?a:typeof a==="number"?!!a:void 0;return a!=null?a:c}
function J(a,b,c){if(c!=null&&typeof c!=="boolean")throw Error("Expected boolean but got "+Ea(c)+": "+c);nc(a);var d=a.h;qc(d,d[F]|0,b,c===!1?void 0:c);return a};function tc(a,b,c){this.h=fc(a,b,c,2048)}tc.prototype.toJSON=function(){var a=ec(this);return a};tc.prototype[Jb]=Wb;tc.prototype.toString=function(){return this.h.toString()};var L=typeof AsyncContext!=="undefined"&&typeof AsyncContext.Snapshot==="function"?function(a){return a&&AsyncContext.Snapshot.wrap(a)}:function(a){return a};var uc=[],vc=[],wc=!1;function xc(a){uc[uc.length]=a;if(wc)for(var b=0;b<vc.length;b++)a(C(vc[b].h,vc[b]))};function N(){this.m=this.m;this.u=this.u}N.prototype.m=!1;N.prototype.isDisposed=function(){return this.m};N.prototype.dispose=function(){this.m||(this.m=!0,this.G())};N.prototype[Symbol.dispose]=function(){this.dispose()};N.prototype.G=function(){if(this.u)for(;this.u.length;)this.u.shift()()};function O(a,b){this.type=a;this.h=this.target=b;this.defaultPrevented=!1}O.prototype.i=function(){this.defaultPrevented=!0};function yc(a,b){O.call(this,a?a.type:"");this.relatedTarget=this.h=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=0;this.key="";this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.j=null;a&&this.init(a,b)}D(yc,O);
yc.prototype.init=function(a,b){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.h=b;b=a.relatedTarget;b||(c=="mouseover"?b=a.fromElement:c=="mouseout"&&(b=a.toElement));this.relatedTarget=b;d?(this.clientX=d.clientX!==void 0?d.clientX:d.pageX,this.clientY=d.clientY!==void 0?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.clientX=a.clientX!==void 0?a.clientX:a.pageX,this.clientY=a.clientY!==
void 0?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.key=a.key||"";this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType=a.pointerType;this.state=a.state;this.j=a;a.defaultPrevented&&yc.K.i.call(this)};yc.prototype.i=function(){yc.K.i.call(this);var a=this.j;a.preventDefault?a.preventDefault():a.returnValue=!1};var zc="closure_listenable_"+(Math.random()*1E6|0);var Ac=0;function Bc(a,b,c,d,e){this.listener=a;this.proxy=null;this.src=b;this.type=c;this.capture=!!d;this.handler=e;this.key=++Ac;this.O=this.R=!1}function Cc(a){a.O=!0;a.listener=null;a.proxy=null;a.src=null;a.handler=null};function Dc(a){this.src=a;this.h={};this.i=0}Dc.prototype.add=function(a,b,c,d,e){var h=a.toString();a=this.h[h];a||(a=this.h[h]=[],this.i++);var f=Ec(a,b,d,e);f>-1?(b=a[f],c||(b.R=!1)):(b=new Bc(b,this.src,h,!!d,e),b.R=c,a.push(b));return b};function Fc(a,b){var c=b.type;c in a.h&&Sa(a.h[c],b)&&(Cc(b),a.h[c].length==0&&(delete a.h[c],a.i--))}function Ec(a,b,c,d){for(var e=0;e<a.length;++e){var h=a[e];if(!h.O&&h.listener==b&&h.capture==!!c&&h.handler==d)return e}return-1};var Gc="closure_lm_"+(Math.random()*1E6|0),Hc={},Ic=0;function Jc(a,b,c,d,e){if(Array.isArray(b))for(var h=0;h<b.length;h++)Jc(a,b[h],c,d,e);else(d=Ga(d)?!!d.capture:!!d,c=Kc(c),a&&a[zc])?(a=a.j,b=String(b).toString(),b in a.h&&(h=a.h[b],c=Ec(h,c,d,e),c>-1&&(Cc(h[c]),Array.prototype.splice.call(h,c,1),h.length==0&&(delete a.h[b],a.i--)))):a&&(a=Lc(a))&&(b=a.h[b.toString()],a=-1,b&&(a=Ec(b,c,d,e)),(c=a>-1?b[a]:null)&&Mc(c))}
function Mc(a){if(typeof a!=="number"&&a&&!a.O){var b=a.src;if(b&&b[zc])Fc(b.j,a);else{var c=a.type,d=a.proxy;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(c in Hc?Hc[c]:Hc[c]="on"+c,d):b.addListener&&b.removeListener&&b.removeListener(d);Ic--;(c=Lc(b))?(Fc(c,a),c.i==0&&(c.src=null,b[Gc]=null)):Cc(a)}}}function Nc(a,b){if(a.O)a=!0;else{b=new yc(b,this);var c=a.listener,d=a.handler||a.src;a.R&&Mc(a);a=c.call(d,b)}return a}
function Lc(a){a=a[Gc];return a instanceof Dc?a:null}var Oc="__closure_events_fn_"+(Math.random()*1E9>>>0);function Kc(a){if(typeof a==="function")return a;a[Oc]||(a[Oc]=function(b){return a.handleEvent(b)});return a[Oc]}xc(function(a){Nc=a(Nc)});function P(){N.call(this);this.j=new Dc(this);this.U=this;this.D=null}D(P,N);P.prototype[zc]=!0;P.prototype.removeEventListener=function(a,b,c,d){Jc(this,a,b,c,d)};
function Q(a,b){var c=a.D;if(c){var d=[];for(var e=1;c;c=c.D)d.push(c),++e}a=a.U;c=b.type||b;typeof b==="string"?b=new O(b,a):b instanceof O?b.target=b.target||a:(e=b,b=new O(c,a),ab(b,e));e=!0;var h;if(d)for(h=d.length-1;h>=0;h--){var f=b.h=d[h];e=Pc(f,c,!0,b)&&e}f=b.h=a;e=Pc(f,c,!0,b)&&e;e=Pc(f,c,!1,b)&&e;if(d)for(h=0;h<d.length;h++)f=b.h=d[h],e=Pc(f,c,!1,b)&&e}
P.prototype.G=function(){P.K.G.call(this);if(this.j){var a=this.j,b=0,c;for(c in a.h){for(var d=a.h[c],e=0;e<d.length;e++)++b,Cc(d[e]);delete a.h[c];a.i--}}this.D=null};function Pc(a,b,c,d){b=a.j.h[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,h=0;h<b.length;++h){var f=b[h];if(f&&!f.O&&f.capture==c){var g=f.listener,k=f.handler||f.src;f.R&&Fc(a.j,f);e=g.call(k,d)!==!1&&e}}return e&&!d.defaultPrevented};function Qc(a){try{return B.JSON.parse(a)}catch(b){}a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);};function Rc(a){switch(a){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:return!0;default:return!1}};function Sc(){};var Tc;function Uc(){}D(Uc,Sc);Uc.prototype.h=function(){return new XMLHttpRequest};Tc=new Uc;var Vc=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function Wc(a){a=a.match(Vc)[1]||null;!a&&B.self&&B.self.location&&(a=B.self.location.protocol.slice(0,-1));return a?a.toLowerCase():""}
function Xc(a,b){if(!b)return a;var c=a.indexOf("#");c<0&&(c=a.length);var d=a.indexOf("?");if(d<0||d>c){d=c;var e=""}else e=a.substring(d+1,c);a=[a.slice(0,d),e,a.slice(c)];c=a[1];a[1]=b?c?c+"&"+b:b:c;return a[0]+(a[1]?"?"+a[1]:"")+a[2]}function Yc(a,b,c){if(Array.isArray(b))for(var d=0;d<b.length;d++)Yc(a,String(b[d]),c);else b!=null&&c.push(a+(b===""?"":"="+encodeURIComponent(String(b))))}function Zc(a,b){var c=[];for(b=b||0;b<a.length;b+=2)Yc(a[b],a[b+1],c);return c.join("&")}
function $c(a){var b=[],c;for(c in a)Yc(c,a[c],b);return b.join("&")}function ad(a,b){var c=arguments.length==2?Zc(arguments[1],0):Zc(arguments,1);return Xc(a,c)};function bd(a){P.call(this);this.headers=new Map;this.P=a||null;this.i=!1;this.h=null;this.C="";this.l=this.B=this.o=this.A=!1;this.F=0;this.v=null;this.L="";this.I=!1}D(bd,P);var cd=/^https?$/i,dd=["POST","PUT"],ed=[];function fd(a,b,c,d,e,h,f){var g=new bd;ed.push(g);b&&g.j.add("complete",b,!1,void 0,void 0);g.j.add("ready",g.ga,!0,void 0,void 0);h&&(g.F=Math.max(0,h));f&&(g.I=f);gd(g,a,c,d,e)}n=bd.prototype;n.ga=function(){this.dispose();Sa(ed,this)};
function gd(a,b,c,d,e){if(a.h)throw Error("[goog.net.XhrIo] Object is active with another request="+a.C+"; newUri="+b);c=c?c.toUpperCase():"GET";a.C=b;a.A=!1;a.i=!0;a.h=a.P?a.P.h():Tc.h();a.h.onreadystatechange=L(C(a.Z,a));try{a.B=!0,a.h.open(c,String(b),!0),a.B=!1}catch(u){id(a);return}b=d||"";d=new Map(a.headers);if(e)if(Object.getPrototypeOf(e)===Object.prototype)for(var h in e)d.set(h,e[h]);else if(typeof e.keys==="function"&&typeof e.get==="function"){h=w(e.keys());var f=h.next(),g;try{for(;!f.done;f=
h.next()){var k=f.value;d.set(k,e.get(k))}}finally{f&&!f.done&&(g=h.return)&&g.call(h)}}else throw Error("Unknown input type for opt_headers: "+String(e));e=Array.from(d.keys()).find(function(u){return"content-type"==u.toLowerCase()});g=B.FormData&&b instanceof B.FormData;!(Oa(dd,c)>=0)||e||g||d.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");c=w(d);e=c.next();var l;try{for(;!e.done;e=c.next()){var m=w(e.value),q=m.next().value,t=m.next().value;a.h.setRequestHeader(q,t)}}finally{e&&
!e.done&&(l=c.return)&&l.call(c)}a.L&&(a.h.responseType=a.L);"withCredentials"in a.h&&a.h.withCredentials!==a.I&&(a.h.withCredentials=a.I);try{jd(a),a.F>0&&(a.v=setTimeout(a.T.bind(a),a.F)),a.o=!0,a.h.send(b),a.o=!1}catch(u){id(a)}}n.T=function(){typeof Ba!="undefined"&&this.h&&(Q(this,"timeout"),this.abort(8))};function id(a){a.i=!1;a.h&&(a.l=!0,a.h.abort(),a.l=!1);kd(a);ld(a)}function kd(a){a.A||(a.A=!0,Q(a,"complete"),Q(a,"error"))}
n.abort=function(){this.h&&this.i&&(this.i=!1,this.l=!0,this.h.abort(),this.l=!1,Q(this,"complete"),Q(this,"abort"),ld(this))};n.G=function(){this.h&&(this.i&&(this.i=!1,this.l=!0,this.h.abort(),this.l=!1),ld(this,!0));bd.K.G.call(this)};n.Z=function(){this.isDisposed()||(this.B||this.o||this.l?md(this):this.V())};n.V=function(){md(this)};
function md(a){if(a.i&&typeof Ba!="undefined")if(a.o&&(a.h?a.h.readyState:0)==4)setTimeout(a.Z.bind(a),0);else if(Q(a,"readystatechange"),(a.h?a.h.readyState:0)==4){a.i=!1;try{try{var b=(a.h?a.h.readyState:0)>2?a.h.status:-1}catch(h){b=-1}var c;if(!(c=Rc(b))){var d;if(d=b===0){var e=Wc(String(a.C));d=!cd.test(e)}c=d}c?(Q(a,"complete"),Q(a,"success")):kd(a)}finally{ld(a)}}}function ld(a,b){if(a.h){jd(a);var c=a.h;a.h=null;b||Q(a,"ready");try{c.onreadystatechange=null}catch(d){}}}
function jd(a){a.v&&(clearTimeout(a.v),a.v=null)}n.isActive=function(){return!!this.h};xc(function(a){bd.prototype.V=a(bd.prototype.V)});function sc(a){this.h=fc(a,void 0,void 0,2048)}v(sc,tc);n=sc.prototype;n.getEnableSsEngine=function(){return H(this,2)};n.getEnableAwr=function(){return H(this,3)};n.getAlohaAutoGaRollout=function(){return H(this,5)};n.getEnableConfigurator=function(){return H(this,6)};n.getEnableMweb=function(){return H(this,7)};function nd(){var a=od();return J(a,7,!0)}n.getEnableCtlConsentCheckbox=function(){return H(this,8)};n.getEnableIframe=function(){return H(this,9)};
function od(){var a=new sc;a=J(a,5,!0);a=J(a,2,!0);a=J(a,4,!1);a=J(a,8,!0);return J(a,9,!0)}n.getEnableScreenshotNudge=function(){return H(this,10)};n.getEnableWebStartupConfigEndpoint=function(){return H(this,11)};n.getEnableJunkNudge=function(){return H(this,12)};n.getEnableConfiguratorLocale=function(){return H(this,13)};n.getEnableTinyNoPointer=function(){return H(this,14)};n.getEnableSupportSessionLogging=function(){return H(this,15)};
n.getEnableFileUploadForScreenshot=function(){return H(this,16)};n.getEnableDirectDeflectionForSingleCategory=function(){return H(this,17)};n.getEnableImageSanitization=function(){return H(this,18)};n.getEnableAlohaBinarySplit=function(){return H(this,19)};n.getEnableDbFeedbackIntents=function(){return H(this,20)};n.getEnableMarkMandatoryFieldsWithRequired=function(){return H(this,21)};n.getEnableFeedbackCategoryCustomUi=function(){return H(this,22)};
n.getEnableRealtimeCtl=function(){return H(this,23)};n.getEnableAlohaHeadless=function(){return H(this,24)};n.getUpdateFeedbackConfirmationClarity=function(){return H(this,25)};n.getEnableViewFeedbackReportsLink=function(){return H(this,26)};function pd(a){this.h=fc(a,void 0,void 0,2048)}v(pd,tc);function qd(a){return rd.some(function(b){return b.test(a)})}var rd=[/https:\/\/sandbox\.google\.com\/tools\/feedback/,/https:\/\/feedback-frontend-qual[a-z0-9.]*\.google\.com\/inapp/,/https:\/\/feedback-frontend-qual[a-z0-9.]*\.google\.com\/tools\/feedback/,/https:\/\/.*\.googleusercontent\.com\/inapp/];var sd="af am ar-EG ar-JO ar-MA ar-SA ar-XB ar az be bg bn bs ca cs cy da de-AT de-CH de el en en-GB en-AU en-CA en-IE en-IN en-NZ en-SG en-XA en-XC en-ZA es es-419 es-AR es-BO es-CL es-CO es-CR es-DO es-EC es-GT es-HN es-MX es-NI es-PA es-PE es-PR es-PY es-SV es-US es-UY es-VE et eu fa fi fil fr-CA fr-CH fr gl gsw gu he hi hr hu hy id in is it iw ja ka kk km kn ko ky ln lo lt lv mk ml mn mo mr ms my nb ne nl no pa pl pt pt-BR pt-PT ro ru si sk sl sq sr-Latn sr sv sw ta te th tl tr uk ur uz vi zh zh-CN zh-HK zh-TW zu".split(" ");var td=ma(["https://www.gstatic.com/uservoice/feedback/client/web/","/main_light_binary.js"]),ud=ma(["https://www.gstatic.com/uservoice/feedback/client/web/","/main_binary__",".js"]);
function vd(a,b){var c;var d=(c=a.formContent)==null?void 0:c.locale;c=d==null?void 0:d.split("-")[0];d=d&&sd.includes(d)?d:c&&sd.includes(c)?c:void 0;d=(d!=null?d:"en").replaceAll("-","_").toLowerCase();var e;c=((e=a.initializationData)==null?0:e.useNightlyRelease)?"nightly":"live";var h;return(b==null?0:(h=b.getEnableAlohaBinarySplit)==null?0:h.call(b))&&!a.headlessReport?qb(td,c):qb(ud,c,d)};function wd(){var a=Error.call(this,"Form is either loading or already opened");this.message=a.message;"stack"in a&&(this.stack=a.stack);this.name="DuplicateFormError"}v(wd,Error);var xd,yd,zd,Ad;
function Bd(a,b,c,d){if(xd&&zd===b)return xd;zd=b;var e=vd(a,d);return xd=b.feedbackV2GlobalObject?Promise.resolve(b.feedbackV2GlobalObject):new Promise(function(h,f){var g=ub(document,"SCRIPT");kb(g,e);g.onload=function(){b.feedbackV2GlobalObject?h(b.feedbackV2GlobalObject):f(Error("feedbackV2GlobalObject not found on window."))};g.onerror=function(){f(Error("Feedback binary script tag failed to load: "+e.toString()))};c.body.appendChild(g)})}
function Cd(a,b,c,d){if(yd&&Ad===b)return yd;Ad=b;var e=vd(a,d);return yd=b.feedbackV2GlobalObject?Promise.resolve(b.feedbackV2GlobalObject):new Promise(function(h,f){var g=ub(document,"SCRIPT");kb(g,e);g.onload=function(){b.feedbackV2GlobalObject?h(b.feedbackV2GlobalObject):f(Error("feedbackV2GlobalObject not found on window."))};g.onerror=function(){f(Error("Feedback binary script tag failed to load: "+e.toString()))};c.body.appendChild(g)})}
function Dd(a,b,c,d,e){e=e===void 0?!0:e;var h,f,g,k,l;return A(function(m){switch(m.h){case 1:return h=Date.now(),m.m(Bd(a,c,d,b),2);case 2:f=m.o;if(!(e||((k=a.initializationData)==null?0:k.useNightlyRelease)||((l=a.initializationData)==null?0:l.isLocalServer))){g=f.initializeFeedbackClient(a,h,b);m.J(3);break}return m.m(f.initializeFeedbackClientAsync(a,h,b),4);case 4:g=m.o;case 3:return g.initiateAloha(),m.return(g)}})}
function Ed(a,b,c,d){var e,h,f;return A(function(g){if(g.h==1)return e=Date.now(),g.m(Cd(a,c,d.document,b),2);if(g.h!=3)return h=g.o,g.m(h.initializeFeedbackClientAsync(a,e,b,d),3);f=g.o;f.initiateAloha();return g.return(f)})}
function Fd(a,b,c){var d=!0;d=d===void 0?!0:d;var e,h,f,g,k,l,m,q;return A(function(t){e=c||B;if(((h=b)==null?0:(g=(f=h).getEnableAlohaBinarySplit)==null?0:g.call(f))&&!a.headlessReport){k=e;if(k.isFormOpened)throw new wd;k.isFormOpened=!0;a.callbacks=a.callbacks||{};l=a.callbacks.onClose||function(){};a.callbacks.onClose=function(u){k.isFormOpened=!1;l(u)};try{return t.return(Ed(a,b,k,e))}catch(u){throw k.isFormOpened=!1,u;}}else{m=e;if(m.isFormOpened)throw new wd;m.isFormOpened=!0;a.callbacks=a.callbacks||
{};q=a.callbacks.onClose||function(){};a.callbacks.onClose=function(u){m.isFormOpened=!1;q(u)};try{return t.return(Dd(a,b,m,e.document,d))}catch(u){throw m.isFormOpened=!1,u;}}t.C()})};function Gd(a,b){return A(function(c){return c.return(new Promise(function(d,e){Number.isInteger(Number(a))&&Number(a)>0?(e=Hd(b!=null?b:"")+"/aloha_form_properties?productId="+a,fd(e,function(h){var f=h.target;h=null;try{var g=JSON,k=g.stringify;if(f.h){var l=f.h.responseText;l.indexOf(")]}'\n")==0&&(l=l.substring(5));b:{if(B.JSON)try{var m=B.JSON.parse(l);break b}catch(u){}m=Qc(l)}}else m=void 0;var q=k.call(g,m);if(q==null||q=="")h=new pd;else{var t=JSON.parse(q);if(!Array.isArray(t))throw Error("dnarr");
Ub(t,32);h=new pd(t)}}catch(u){k=new pd;m=nd();m=J(m,10,!0);m=J(m,12,!0);m=J(m,13,!1);m=J(m,14,!0);m=J(m,15,!0);m=J(m,20,!1);m=J(m,25,!1);m=J(m,26,!1);q=sc;if(m!=null){if(!(m instanceof q))throw Error("Expected instanceof "+$b(q)+" but got "+(m&&$b(m.constructor)));}else m=void 0;q=m;nc(k);t=k.h;qc(t,t[F]|0,1,q);m&&!Xb(m)&&oc(k.h);h=k}d(h)},"GET","",{},2E3,!0)):e(Error("Invalid product id: "+a))}))})}function Hd(a){return qd(a)?a:"https://www.google.com/tools/feedback"};Ca("userfeedback.ColorSchemes",{ya:1,pa:2});
function Id(a,b,c,d){a.timeOfStartCall=(new Date).getTime();var e=c||B,h=e.document,f=a.nonce||jb(e.document);f&&!a.nonce&&(a.nonce=f);if(a.flow=="help"){var g=Da("document.location.href",e);!a.helpCenterContext&&g&&(a.helpCenterContext=g.substring(0,1200));g=!0;if(b&&JSON&&JSON.stringify){var k=JSON.stringify(b);(g=k.length<=1200)&&(a.psdJson=k)}g||(b={invalidPsd:!0})}b=[a,b,c,d];e.GOOGLE_FEEDBACK_START_ARGUMENTS=b;c=a.feedbackServerUri||"//www.google.com/tools/feedback";if(d=e.GOOGLE_FEEDBACK_START)d.apply(e,
b);else{e=c+"/load.js?";for(var l in a)b=a[l],b==null||Ga(b)||(e+=encodeURIComponent(l)+"="+encodeURIComponent(b)+"&");a=h?new xb(wb(h)):Na||(Na=new xb);a=ub(a.h,"SCRIPT");f&&a.setAttribute("nonce",f);f=fb(e);kb(a,f);h.body.appendChild(a)}}
function Jd(a,b,c,d){var e,h,f,g,k,l,m,q,t,u,K,G,hd;return A(function(ha){if(ha.h==1)return e=a.flow==="submit",h=!!pb,f=typeof window!=="undefined"&&!!(window.__karma__||window.jasmine||window.mocha||window.jest),e&&f?(Id(a,b,c,d),ha.return()):ha.m(Gd(a.productId,a.feedbackServerUri),2);g=ha.o;if((k=g)==null)var I=void 0;else{I=k.h;var U=I[F]|0,ia=rc(I,U);if(ia!=null&&(U=I[F]|0,!Xb(k,U))){var M=ia;var Pa=M.h,Ob=Pa[F]|0;M=Xb(M,Ob)?kc(M,Pa,Ob)?lc(M,Pa,!0):new M.constructor(jc(Pa,Ob,!1)):M;M!==ia&&
(mc(k)&&(I=k.h,U=I[F]|0),ia=M,U=qc(I,U,1,ia),oc(I,U))}I=ia}l=I;q=!h||((m=l)==null?void 0:m.getEnableMweb());u=!a.tinyNoPointer||((t=l)==null?void 0:t.getEnableTinyNoPointer());K=!e&&(!l||l.getAlohaAutoGaRollout()&&q&&u);hd=e&&((G=l)==null?void 0:G.getEnableAlohaHeadless())&&a.report;return K||hd?ha.m(Kd(a,b,c,l,d),0):(Id(a,b,c,d),ha.J(0))})}
function Kd(a,b,c,d,e){var h,f;return A(function(g){h=c||B;var k=a.serverEnvironment==="DEV",l=c||B;l=a.nonce||jb(l.document);k={integrationKeys:{productId:a.productId,feedbackBucket:a.bucket,triggerId:a.triggerId,microfeedbackScore:a.microfeedbackScore},callbacks:{onClose:a.callback,onLoad:a.onLoadCallback},formContent:{locale:a.locale,disableScreenshot:a.disableScreenshotting,productDisplayName:void 0,announcement:void 0,issueCategories:void 0,includeSeveritySelection:void 0,customImageSrc:void 0,
thankYouMessage:void 0,Ha:void 0,defaultFormInputValues:void 0,defaultFormInputValuesString:void 0,abuseLink:a.abuseLink,additionalDataConsent:a.additionalDataConsent},initializationData:{isLocalServer:k,nonce:l,useNightlyRelease:k,feedbackJsUrl:void 0,feedbackCssUrl:void 0,feedbackJsUrlSerialized:void 0,feedbackCssUrlSerialized:void 0,submissionServerUri:a.feedbackServerUri,colorScheme:a.colorScheme},extraData:{productVersion:a.productVersion,authUser:a.authuser,configuratorId:a.configuratorId,customZIndex:a.customZIndex,
tinyNoPointer:a.tinyNoPointer,allowNonLoggedInFeedback:a.allowNonLoggedInFeedback,enableAnonymousFeedback:a.enableAnonymousFeedback}};a.report&&a.flow==="submit"&&(k.headlessReport=a.report);b&&(l=new Map(Object.entries(b)),k.extraData.productSpecificData=l);e&&(l=new Map(Object.entries(e)),k.extraData.productSpecificBinaryData=l);f=k;return g.m(Fd(f,d,h),0)})}
Ca("userfeedback.api.startFeedback",function(a,b,c,d){try{if(a.flow==="help"){var e=a.helpCenterPath.replace(/^\//,"");ib(c||window,"https://support.google.com/"+e)}else Jd(a,b,c,d).catch(function(h){!h||h instanceof wd||Id(a,b,c,d)})}catch(h){Kd(a,b,c,null,d).catch(function(f){!f||f instanceof wd||Id(a,b,c,d)})}});function Ld(a,b){this.j=a;this.l=b;this.i=0;this.h=null}Ld.prototype.get=function(){if(this.i>0){this.i--;var a=this.h;this.h=a.next;a.next=null}else a=this.j();return a};function Md(a,b){a.l(b);a.i<100&&(a.i++,b.next=a.h,a.h=b)};xc(function(){});function Nd(){this.i=this.h=null}Nd.prototype.add=function(a,b){var c=Od.get();c.set(a,b);this.i?this.i.next=c:this.h=c;this.i=c};function Pd(){var a=Qd,b=null;a.h&&(b=a.h,a.h=a.h.next,a.h||(a.i=null),b.next=null);return b}var Od=new Ld(function(){return new Rd},function(a){return a.reset()});function Rd(){this.next=this.scope=this.h=null}Rd.prototype.set=function(a,b){this.h=a;this.scope=b;this.next=null};Rd.prototype.reset=function(){this.next=this.scope=this.h=null};var Sd,Td=!1,Qd=new Nd;function Ud(a,b){Sd||Vd();Td||(Sd(),Td=!0);Qd.add(a,b)}function Vd(){var a=Promise.resolve(void 0);Sd=function(){a.then(Wd)}}function Wd(){for(var a;a=Pd();){try{a.h.call(a.scope)}catch(b){yb(b)}Md(Od,a)}Td=!1};function Xd(){};function Yd(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};function R(a){this.h=0;this.u=void 0;this.l=this.i=this.j=null;this.m=this.o=!1;if(a!=Xd)try{var b=this;a.call(void 0,function(c){S(b,2,c)},function(c){S(b,3,c)})}catch(c){S(this,3,c)}}function Zd(){this.next=this.j=this.i=this.l=this.h=null;this.m=!1}Zd.prototype.reset=function(){this.j=this.i=this.l=this.h=null;this.m=!1};var $d=new Ld(function(){return new Zd},function(a){a.reset()});function ae(a,b,c){var d=$d.get();d.l=a;d.i=b;d.j=c;return d}
function be(a){if(a instanceof R)return a;var b=new R(Xd);S(b,2,a);return b}function ce(a,b,c){de(a,b,c,null)||Ud(La(b,a))}function ee(a){return new R(function(b){var c=a.length,d=[];if(c)for(var e=function(g,k,l){c--;d[g]=k?{ia:!0,value:l}:{ia:!1,reason:l};c==0&&b(d)},h,f=0;f<a.length;f++)h=a[f],ce(h,La(e,f,!0),La(e,f,!1));else b(d)})}R.prototype.then=function(a,b,c){return fe(this,L(typeof a==="function"?a:null),L(typeof b==="function"?b:null),c)};R.prototype.$goog_Thenable=!0;
function ge(a,b){return fe(a,null,L(b))}R.prototype.cancel=function(a){if(this.h==0){var b=new he(a);Ud(function(){ie(this,b)},this)}};function ie(a,b){if(a.h==0)if(a.j){var c=a.j;if(c.i){for(var d=0,e=null,h=null,f=c.i;f&&(f.m||(d++,f.h==a&&(e=f),!(e&&d>1)));f=f.next)e||(h=f);e&&(c.h==0&&d==1?ie(c,b):(h?(d=h,d.next==c.l&&(c.l=d),d.next=d.next.next):je(c),ke(c,e,3,b)))}a.j=null}else S(a,3,b)}function le(a,b){a.i||a.h!=2&&a.h!=3||me(a);a.l?a.l.next=b:a.i=b;a.l=b}
function fe(a,b,c,d){var e=ae(null,null,null);e.h=new R(function(h,f){e.l=b?function(g){try{var k=b.call(d,g);h(k)}catch(l){f(l)}}:h;e.i=c?function(g){try{var k=c.call(d,g);k===void 0&&g instanceof he?f(g):h(k)}catch(l){f(l)}}:f});e.h.j=a;le(a,e);return e.h}R.prototype.A=function(a){this.h=0;S(this,2,a)};R.prototype.B=function(a){this.h=0;S(this,3,a)};
function S(a,b,c){a.h==0&&(a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself")),a.h=1,de(c,a.A,a.B,a)||(a.u=c,a.h=b,a.j=null,me(a),b!=3||c instanceof he||ne(a,c)))}function de(a,b,c,d){if(a instanceof R)return le(a,ae(b||Xd,c||null,d)),!0;if(Yd(a))return a.then(b,c,d),!0;if(Ga(a))try{var e=a.then;if(typeof e==="function")return oe(a,e,b,c,d),!0}catch(h){return c.call(d,h),!0}return!1}
function oe(a,b,c,d,e){function h(k){g||(g=!0,d.call(e,k))}function f(k){g||(g=!0,c.call(e,k))}var g=!1;try{b.call(a,f,h)}catch(k){h(k)}}function me(a){a.o||(a.o=!0,Ud(a.v,a))}function je(a){var b=null;a.i&&(b=a.i,a.i=b.next,b.next=null);a.i||(a.l=null);return b}R.prototype.v=function(){for(var a;a=je(this);)ke(this,a,this.h,this.u);this.o=!1};
function ke(a,b,c,d){if(c==3&&b.i&&!b.m)for(;a&&a.m;a=a.j)a.m=!1;if(b.h)b.h.j=null,pe(b,c,d);else try{b.m?b.l.call(b.j):pe(b,c,d)}catch(e){qe.call(null,e)}Md($d,b)}function pe(a,b,c){b==2?a.l.call(a.j,c):a.i&&a.i.call(a.j,c)}function ne(a,b){a.m=!0;Ud(function(){a.m&&qe.call(null,b)})}var qe=yb;function he(a){E.call(this,a);this.h=!1}D(he,E);he.prototype.name="cancel";function re(a){a=a===void 0?{}:a;this.useNotifications=a.useNotifications||!1;this.operatorDeferredUrl=a.operatorDeferredUrl;this.alphaTestMode=a.alphaTestMode||!1;this.stagingMode=a.stagingMode||!1;this.disableCustomerInitialization=a.disableCustomerInitialization||!1;this.rosterId=a.rosterId||"talk_roster";this.feedbackId=a.feedbackId||74772;this.moleVersion=a.moleVersion||void 0;this.gstaticBaseUrl=a.gstaticBaseUrl||void 0;this.operatorDeferredBaseUrl=a.operatorDeferredBaseUrl||void 0;this.forceLeftMoles=
a.forceLeftMoles||void 0;this.helpCenterName=a.helpCenterName||null;this.localeName=a.localeName||null;this.document=a.document||document;this.source=a.source||void 0;this.entityId=a.entityId||void 0;this.authUser=a.authUser||void 0;this.appDomain=a.appDomain||void 0;this.apiKey=a.apiKey||void 0;this.hideQueueWidget=a.hideQueueWidget||!1;this.hideMoles=a.hideMoles||!1;this.enableMinimizeRestoreKeyboardShortcut=a.enableMinimizeRestoreKeyboardShortcut||!1;this.showSecondsInChatTranscript=a.showSecondsInChatTranscript||
!1;this.settings=a.settings||void 0;this.jsHint=a.jsHint||void 0;this.xhrTimeoutMs=a.xhrTimeoutMs||3E4;this.enableChatSmartReply=a.enableChatSmartReply||!1;this.isCasesHostPage=a.isCasesHostPage||!1};/*

 Copyright 2005, 2007 Bob Ippolito. All Rights Reserved.
 Copyright The Closure Library Authors.
 SPDX-License-Identifier: MIT
*/
function T(a){var b=se;this.m=[];this.D=b;this.C=a||null;this.l=this.j=!1;this.i=void 0;this.A=this.F=this.u=!1;this.o=0;this.h=null;this.v=0}T.prototype.cancel=function(a){if(this.j)this.i instanceof T&&this.i.cancel();else{if(this.h){var b=this.h;delete this.h;a?b.cancel(a):(b.v--,b.v<=0&&b.cancel())}this.D?this.D.call(this.C,this):this.A=!0;this.j||(a=new te(this),ue(this),ve(this,!1,a))}};T.prototype.B=function(a,b){this.u=!1;ve(this,a,b)};function ve(a,b,c){a.j=!0;a.i=c;a.l=!b;we(a)}
function ue(a){if(a.j){if(!a.A)throw new xe(a);a.A=!1}}T.prototype.callback=function(a){ue(this);ve(this,!0,a)};function ye(a,b,c,d){var e=a.j;e||(b===c?b=c=L(b):(b=L(b),c=L(c)));a.m.push([b,c,d]);e&&we(a)}T.prototype.then=function(a,b,c){var d,e,h=new R(function(f,g){e=f;d=g});ye(this,e,function(f){f instanceof te?h.cancel():d(f);return ze},this);return h.then(a,b,c)};T.prototype.$goog_Thenable=!0;function Ae(a){return Ra(a.m,function(b){return typeof b[1]==="function"})}var ze={};
function we(a){if(a.o&&a.j&&Ae(a)){var b=a.o,c=Be[b];c&&(B.clearTimeout(c.h),delete Be[b]);a.o=0}a.h&&(a.h.v--,delete a.h);b=a.i;for(var d=c=!1;a.m.length&&!a.u;){var e=a.m.shift(),h=e[0],f=e[1];e=e[2];if(h=a.l?f:h)try{var g=h.call(e||a.C,b);g===ze&&(g=void 0);g!==void 0&&(a.l=a.l&&(g==b||g instanceof Error),a.i=b=g);if(Yd(b)||typeof B.Promise==="function"&&b instanceof B.Promise)d=!0,a.u=!0}catch(k){b=k,a.l=!0,Ae(a)||(c=!0)}}a.i=b;d&&(g=C(a.B,a,!0),d=C(a.B,a,!1),b instanceof T?(ye(b,g,d),b.F=!0):
b.then(g,d));c&&(b=new Ce(b),Be[b.h]=b,a.o=b.h)}function xe(){E.call(this)}D(xe,E);xe.prototype.message="Deferred has already fired";xe.prototype.name="AlreadyCalledError";function te(){E.call(this)}D(te,E);te.prototype.message="Deferred was canceled";te.prototype.name="CanceledError";function Ce(a){this.h=B.setTimeout(C(this.j,this),0);this.i=a}Ce.prototype.j=function(){delete Be[this.h];throw this.i;};var Be={};function De(a,b){var c=b||{};b=c.document||document;var d=gb(a).toString(),e=ub((new xb(b)).h,"SCRIPT"),h={aa:e,T:void 0},f=new T(h),g=null,k=c.timeout!=null?c.timeout:5E3;k>0&&(g=window.setTimeout(function(){Ee(e,!0);var l=new Fe(1,"Timeout reached for loading script "+d);ue(f);ve(f,!1,l)},k),h.T=g);e.onload=e.onreadystatechange=function(){e.readyState&&e.readyState!="loaded"&&e.readyState!="complete"||(Ee(e,c.Fa||!1,g),f.callback(null))};e.onerror=function(){Ee(e,!0,g);var l=new Fe(0,"Error while loading script "+
d);ue(f);ve(f,!1,l)};h=c.attributes||{};ab(h,{type:"text/javascript",charset:"UTF-8"});rb(e,h);kb(e,a);Ge(b).appendChild(e);return f}function Ge(a){var b;return(b=(a||document).getElementsByTagName("HEAD"))&&b.length!==0?b[0]:a.documentElement}function se(){if(this&&this.aa){var a=this.aa;a&&a.tagName=="SCRIPT"&&Ee(a,!0,this.T)}}
function Ee(a,b,c){c!=null&&B.clearTimeout(c);a.onload=function(){};a.onerror=function(){};a.onreadystatechange=function(){};b&&window.setTimeout(function(){a&&a.parentNode&&a.parentNode.removeChild(a)},0)}function Fe(a,b){var c="Jsloader error (code #"+a+")";b&&(c+=": "+b);E.call(this,c);this.code=a}D(Fe,E);function He(a,b){return Ie(a,b).then(function(c){var d=c.responseText;b&&b.na&&(c=b.na,d.lastIndexOf(c,0)==0&&(d=d.substring(c.length)));return JSON.parse(d)})}
function Ie(a,b){var c=b||{},d=c.ca?c.ca.h():Tc.h();return ge(new R(function(e,h){var f;try{d.open("GET",a,!0)}catch(l){h(new V("Error opening XHR: "+l.message,a,d))}d.onreadystatechange=function(){if(d.readyState==4){B.clearTimeout(f);var l;!(l=Rc(d.status))&&(l=d.status===0)&&(l=Wc(a),l=!(l=="http"||l=="https"||l==""));l?e(d):h(new Je(d.status,a,d))}};d.onerror=function(){h(new V("Network error",a,d))};if(c.headers)for(var g in c.headers){var k=c.headers[g];k!=null&&d.setRequestHeader(g,k)}c.withCredentials&&
(d.withCredentials=c.withCredentials);c.responseType&&(d.responseType=c.responseType);c.mimeType&&d.overrideMimeType(c.mimeType);c.ba>0&&(f=B.setTimeout(function(){d.onreadystatechange=function(){};d.abort();h(new Ke(a,d))},c.ba));try{d.send(null)}catch(l){d.onreadystatechange=function(){},B.clearTimeout(f),h(new V("Error sending XHR: "+l.message,a,d))}}),function(e){e instanceof he&&d.abort();throw e;})}function V(a,b){E.call(this,a+", url="+b);this.url=b}D(V,E);V.prototype.name="XhrError";
function Je(a,b,c){V.call(this,"Request Failed, status="+a,b,c);this.status=a}D(Je,V);Je.prototype.name="XhrHttpError";function Ke(a,b){V.call(this,"Request timed out",a,b)}D(Ke,V);Ke.prototype.name="XhrTimeoutError";function Le(){}D(Le,Sc);Le.prototype.h=function(){var a=new XMLHttpRequest;if("withCredentials"in a)return a;if(typeof XDomainRequest!="undefined")return new Me;throw Error("Unsupported browser");};function Me(){this.h=new XDomainRequest;this.readyState=0;this.onreadystatechange=null;this.responseType=this.responseText="";this.status=-1;this.statusText="";this.h.onload=C(this.ja,this);this.h.onerror=C(this.W,this);this.h.onprogress=C(this.ka,this);this.h.ontimeout=C(this.la,this)}n=Me.prototype;
n.open=function(a,b,c){if(c!=null&&!c)throw Error("Only async requests are supported.");this.h.open(a,b)};n.send=function(a){if(a)if(typeof a=="string")this.h.send(a);else throw Error("Only string data is supported");else this.h.send()};n.abort=function(){this.h.abort()};n.setRequestHeader=function(){};n.getResponseHeader=function(a){return a.toLowerCase()=="content-type"?this.h.contentType:""};n.ja=function(){this.status=200;this.responseText=this.h.responseText;Ne(this,4)};
n.W=function(){this.status=500;this.responseText="";Ne(this,4)};n.la=function(){this.W()};n.ka=function(){this.status=200;Ne(this,1)};function Ne(a,b){a.readyState=b;if(a.onreadystatechange)a.onreadystatechange()}n.getAllResponseHeaders=function(){return"content-type: "+this.h.contentType};function Oe(a){this.config=a instanceof re?a:new re(a);this.config=Pe(this.config);this.h=Qe(this);this.j=this.config.moleVersion?be():this.h.then(function(b){this.config.moleVersion=b.cbfVersion;this.config.screenShareVersion=b.screenShareVersion},function(){},this);this.l=this.h.then(function(b){this.config.settings=this.config.settings?Object.assign({},b.settings,this.config.settings):b.settings},function(){},this);this.h.then(this.i,function(){},this)}
function Qe(a){return He(a.config.alphaTestMode?"//ssl.gstatic.com/support/realtime/operatorParamsDev":a.config.stagingMode?"//ssl.gstatic.com/support/realtime/operatorParamsStaging":"//ssl.gstatic.com/support/realtime/operatorParams",{ba:a.config.xhrTimeoutMs,ca:new Le}).then(function(b){if(!b)throw Error("operatorParams is null");return b},function(b){throw b;})}
function Re(a){var b=Se();if(b)return b;if(b=Da("cs.operatorDeferredInstance"))return b=be(b),Te(b),b;b=ee([a.j,a.l]).then(function(){return Ue(a).then(function(c){var d={document:this.config.document,timeout:this.config.xhrTimeoutMs};this.config.operatorDeferredUrl=c;try{return De(fb(c===null?"null":c===void 0?"undefined":c),d).then(function(){return B.cs.OperatorDeferred.getInstance(this.config)},function(e){throw e;},this)}catch(e){throw e;}},null,a)},function(){},a);Te(b);return b}
Oe.prototype.i=function(a){(new RegExp(a.eagerLoadHostnamePattern,a.eagerLoadHostnameFlags)).test(this.config.document.location.href)&&ge(Re(this),La(Ve,"Error retrieving OperatorDeferred"))};
function Ue(a){return a.config.operatorDeferredUrl?be(a.config.operatorDeferredUrl):a.config.operatorDeferredBaseUrl?(a=a.config.operatorDeferredBaseUrl+"/"+a.config.moleVersion+"/operatordeferred_bin_base__"+a.config.localeName.replace(/-/g,"_").toLowerCase()+".js",be(a)):a.h.then(C(function(b){return"https://ssl.gstatic.com/support/realtime/operator/"+b.cbfVersion+"/operatordeferred_bin_base__"+this.config.localeName.replace(/-/g,"_").toLowerCase()+".js"},a),function(b){throw b;})}
function We(a,b){return Re(a).then(La(function(c,d){d.registerAvailabilityCallbacks(c)},b))}Oe.prototype.N=function(){return Re(this).then(function(a){a.ensureSubscribed()})};function Se(){var a=Da("cs.operatorDeferredPromise");return a instanceof R?a:a!=null?be(a):null}function Te(a){Ca("cs.operatorDeferredPromise",a)}function Ve(){}
function Pe(a){a=Za(a);a.document=a.document||document;a.localeName!=null&&(a.localeName=a.localeName.replace(/_/g,"-"));a.localeName=a.localeName&&Oa(Xe,a.localeName)>=0?a.localeName:"en";a.helpCenterName=a.helpCenterName||"chatsupport";a.apiKey=a.apiKey||"AIzaSyB5V4SIBGmrqREm7kf2fBJgPcBMCdUrLzE";return a}var Xe="af am ar ar-XB bg bn ca cs da de el en en-AU en-GB en-XA en-XC es es-419 et eu fa fi fil fr gl gu hi hr hu id is it iw ja kn ko lt lv ml mr ms nl no pl pt-PT pt-BR ro ru sk sl sr sv sw ta te th tr uk ur vi zh-CN zh-TW zh-HK zu".split(" ");function Ye(a){Oe.call(this,a)}v(Ye,Oe);function Ze(a){N.call(this);this.i=a}D(Ze,N);Ze.prototype.h=function(a){return $e(this,a)};function af(a,b){a=Object.prototype.hasOwnProperty.call(a,Ha)&&a[Ha]||(a[Ha]=++Ia);return(b?"__wrapper_":"__protected_")+a+"__"}function $e(a,b){var c=af(a,!0);b[c]||((b[c]=bf(a,b))[af(a,!1)]=b);return b[c]}
function bf(a,b){function c(){if(a.isDisposed())return b.apply(this,arguments);try{return b.apply(this,arguments)}catch(e){var d=e;if(!(d&&typeof d==="object"&&typeof d.message==="string"&&d.message.indexOf("Error in protected function: ")==0||typeof d==="string"&&d.indexOf("Error in protected function: ")==0))throw a.i(d),new cf(d);}}c[af(a,!1)]=b;return c}
function df(a,b){var c=B.window||B.globalThis,d=c[b];if(!d)throw Error(b+" not on global?");c[b]=function(e,h){typeof e==="string"&&(e=La(Ma,e));e&&(arguments[0]=e=$e(a,e));if(d.apply)return d.apply(this,arguments);var f=e;if(arguments.length>2){var g=Array.prototype.slice.call(arguments,2);f=function(){e.apply(this,g)}}return d(f,h)};c[b][af(a,!1)]=d}
Ze.prototype.G=function(){var a=B.window||B.globalThis;var b=a.setTimeout;b=b[af(this,!1)]||b;a.setTimeout=b;b=a.setInterval;b=b[af(this,!1)]||b;a.setInterval=b;Ze.K.G.call(this)};function cf(a){E.call(this,"Error in protected function: "+(a&&a.message?String(a.message):String(a)),a);(a=a&&a.stack)&&typeof a==="string"&&(this.stack=a)}D(cf,E);function ef(a,b,c){P.call(this);this.l=b||null;this.i={};this.A=ff;this.v=a;if(!c){this.h=null;this.h=new Ze(C(this.o,this));df(this.h,"setTimeout");df(this.h,"setInterval");a=this.h;b=B.window||B.globalThis;c=["requestAnimationFrame","mozRequestAnimationFrame","webkitAnimationFrame","msRequestAnimationFrame"];for(var d=0;d<c.length;d++){var e=c[d];c[d]in b&&df(a,e)}a=this.h;wc=!0;b=C(a.h,a);for(c=0;c<uc.length;c++)uc[c](b);vc.push(a)}}D(ef,P);function gf(a){O.call(this,"a");this.error=a}D(gf,O);
function ff(a,b,c,d){if(d instanceof Map){var e={};d=w(d);var h=d.next(),f;try{for(;!h.done;h=d.next()){var g=w(h.value),k=g.next().value,l=g.next().value;e[k]=l}}finally{h&&!h.done&&(f=d.return)&&f.call(d)}}else e=d;fd(a,null,b,c,e)}
ef.prototype.o=function(a,b){a=a.error||a;b=b?Za(b):{};a instanceof Error&&ab(b,a.__closure__error__context__984382||{});var c=Ua(a);if(this.l)try{this.l(c,b,a)}catch(t){}var d=c.message.substring(0,1900);if(!(a instanceof E)||a.h){var e=c.fileName,h=c.lineNumber;a=c.stack;try{var f=ad(this.v,"script",e,"error",d,"line",h);a:{for(var g in this.i){var k=!1;break a}k=!0}if(!k){k=f;var l=$c(this.i);f=Xc(k,l)}l={};l.trace=a;if(b)for(var m in b)l["context."+m]=b[m];var q=$c(l);this.A(f,"POST",q,this.B)}catch(t){}}try{Q(this,
new gf(c,b))}catch(t){}};ef.prototype.G=function(){var a=this.h;a&&typeof a.dispose=="function"&&a.dispose();ef.K.G.call(this)};function W(a,b,c,d,e,h){var f=new ef("//www.google.com/tools/feedback/jserror",void 0,!0);this.m=C(f.o,f);this.A=a;this.C=c||"en";this.B=b||!1;this.F=!!d;this.v=e;this.j=this.h=null;this.u=h}
function hf(a,b,c,d,e,h){if(jf())return null;window.top.GOOGLE_HELP_CHAT_OPERATOR_V2=Ye;if(window.top.GOOGLE_HELP_CHAT_SUPPORT)return null;a=new W(a,b,c,d,e,h);window.top.GOOGLE_HELP_CHAT_SUPPORT=a;kf(a);window.addEventListener("message",function(f){f.data==="helpPanelEnsureSubscribed"&&lf.test(f.origin)&&(window.top.GOOGLE_HELP_CHAT_SUPPORT.N(),console.log("Chat ensureSubscribed called by HP event listener."))});return a}
function jf(){var a=window;try{return a==null||a.top==null||a.top.document==null}catch(b){return!0}}function kf(a){var b={helpCenterName:a.A,localeName:a.C,source:1,rosterId:"roster-for-Google-Help",isRtl:a.B,alphaTestMode:!1,stagingMode:a.F,timeoutMs:2E4,authUser:a.v,apiKey:a.u},c=tb("DIV",{id:"roster-for-Google-Help",style:"display: none"});window.top.document.body.appendChild(c);try{a.l=new Ye(b)}catch(d){a.m(d)}}function mf(a,b,c){if(b!=null&&c!=null){var d={};d[b]=c;ge(We(a.l,d),a.m)}}
W.prototype.o=function(a){this.h=a;mf(this,this.h,this.i)};W.prototype.D=function(a){this.i=a;mf(this,this.h,this.i)};W.prototype.N=function(){this.l.N()};var lf=new RegExp(/^https:\/\/(pay.*|billing-ads-qa-devel|daily-1|dasher-workspace-*|madden.*|meet-dev|orderfood-autopush|orderfood-staging|gpay-landing.*|spot.*|subscribe-qual|tokenized.*)?\.?(bpui0|corp|developers|food|maps|meet|news|orderfood|payments|pay|play|sandbox|workspace|www)\.(google|youtube|admob)\.\w+\.?\w*/);
W.prototype.setChatPool=W.prototype.o;W.prototype.setChatCallback=W.prototype.D;W.prototype.ensureSubscribed=W.prototype.N;function nf(){}nf.prototype.next=function(){return of};var of={done:!0,value:void 0};nf.prototype.M=function(){return this};function pf(a){if(a instanceof X||a instanceof qf||a instanceof Y)return a;if(typeof a.next=="function")return new X(function(){return a});if(typeof a[Symbol.iterator]=="function")return new X(function(){return a[Symbol.iterator]()});if(typeof a.M=="function")return new X(function(){return a.M()});throw Error("Not an iterator or iterable.");}function X(a){this.h=a}X.prototype.M=function(){return new qf(this.h())};X.prototype[Symbol.iterator]=function(){return new Y(this.h())};X.prototype.i=function(){return new Y(this.h())};
function qf(a){this.h=a}v(qf,nf);qf.prototype.next=function(){return this.h.next()};qf.prototype[Symbol.iterator]=function(){return new Y(this.h)};qf.prototype.i=function(){return new Y(this.h)};function Y(a){X.call(this,function(){return a});this.j=a}v(Y,X);Y.prototype.next=function(){return this.j.next()};function rf(){};function sf(){}D(sf,rf);sf.prototype[Symbol.iterator]=function(){return pf(this.M(!0)).i()};sf.prototype.clear=function(){var a=Array.from(this);a=w(a);var b=a.next(),c;try{for(;!b.done;b=a.next()){var d=b.value;Z(this);this.h.removeItem(d)}}finally{b&&!b.done&&(c=a.return)&&c.call(a)}};function tf(a){this.h=a;this.i=null}D(tf,sf);n=tf.prototype;n.set=function(a,b){Z(this);try{this.h.setItem(a,b)}catch(c){if(this.h.length==0)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};n.get=function(a){Z(this);a=this.h.getItem(a);if(typeof a!=="string"&&a!==null)throw"Storage mechanism: Invalid value was encountered";return a};
n.M=function(a){Z(this);var b=0,c=this.h,d=new nf;d.next=function(){if(b>=c.length)return of;var e=c.key(b++);if(a)return{value:e,done:!1};e=c.getItem(e);if(typeof e!=="string")throw"Storage mechanism: Invalid value was encountered";return{value:e,done:!1}};return d};n.clear=function(){Z(this);this.h.clear()};n.key=function(a){Z(this);return this.h.key(a)};
function Z(a){if(a.h==null)throw Error("Storage mechanism: Storage unavailable");if(a.i===null){var b=a.h;if(b)try{b.setItem("__sak","1");b.removeItem("__sak");var c=!0}catch(d){c=d instanceof DOMException&&(d.name==="QuotaExceededError"||d.code===22||d.code===1014||d.name==="NS_ERROR_DOM_QUOTA_REACHED")&&b&&b.length!==0}else c=!1;a.i=c}a.i||yb(Error("Storage mechanism: Storage unavailable"))};function uf(){var a=null;try{a=B.sessionStorage||null}catch(b){}tf.call(this,a)}D(uf,tf);function vf(){N.call(this);this.h=new uf}v(vf,N);vf.prototype.clear=function(){var a=this.h;Z(a);a.h.removeItem("GOOGLE_HELP_SESSION_STATE")};(function(a){var b=a.helpCenterPath,c=a.locale,d=a.authuser,e=a.escalationJSONString,h=!!a.useStagingServer;a=a.apiKey;var f=document.body;a:{var g=wb(f);if(g.defaultView&&g.defaultView.getComputedStyle&&(g=g.defaultView.getComputedStyle(f,null))){g=g.direction||g.getPropertyValue("direction")||"";break a}g=""}b=hf(b,"rtl"==(g||(f.currentStyle?f.currentStyle.direction:null)||f.style&&f.style.direction),c,h,d,a);c=new vf;e&&(c.clear(),e={ha:JSON.parse(e).ha},e.sessionTimestamp=(new Date).getTime(),
c.h.set("GOOGLE_HELP_SESSION_STATE",JSON.stringify(e)));if(e=c.h.get("GOOGLE_HELP_SESSION_STATE")){if(e=JSON.parse(e),d=(new Date).getTime(),h=e.sessionTimestamp,!h||typeof h!=="number"||d>h+6E4)c.clear(),e=null}else e=null;c=(e||{}).escalationOptions;if(b&&c){e=c.hangout||{};(c=(c.chat||{}).chat_pool_id)&&b.o(c);if(e=e.hangout_pool_id)b.j=e,mf(b,b.j,b.I);b.N()}}).apply(B,B.GOOGLE_HELP_CHAT_ARGUMENTS);}).call(this);
